/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define ADC1_BASE_ADDRESS  				0x50000000UL
#define ADC1_CONTROL_REGISTER_OFFSET	0x08UL
#define ADC1_CONTROL_REGISTER_ADDRESS   (ADC1_BASE_ADDRESS+ADC1_CONTROL_REGISTER_OFFSET)

#define RCC_AHBENR_OFFSET 				0x14UL
#define RCC_AHBENR_BASE_ADDRESS 		0x40021000UL
#define RCC_AHBENR_ADDRESS 				(RCC_AHBENR_BASE_ADDRESS+RCC_AHBENR_OFFSET)

int main(void)
{
	//Enable clock

	uint32_t *ptr_ADC1_CR =   (uint32_t*) ADC1_CONTROL_REGISTER_ADDRESS;
	uint32_t *RCC_AHBEN =  (uint32_t*) RCC_AHBENR_ADDRESS;

		//1.Enable the peripheral clock for ADC1
		*RCC_AHBEN |= ( 1 << 28);

	    //2. modify the ADC cr1 register
		*ptr_ADC1_CR |= ( 1 << 31);


    /* Loop forever */
	for(;;);
}
